### PR TITLE
Java 17 version by @GavinRay97

### LINKED ISSUE #1: Updated with JDK17 sealed interfaces and pattern match switch =)
The biggest difference is mostly being able to do this:
```java
// def add(a: Value, b: Value): M[Value] = Pair(a, b) match {
//   case Pair(Num(m), Num(n)) => unitM(Num(m + n))
//   case _ => unitM(Wrong)
// }
static M<Value> add(Value a, Value b) {
  // I am actually not sure if this is valid, didn't test it
  // (Switching on generics. It may not work, but my IDE gave me proper autocomplete)
  return switch (Pair(a, b)) {
    case Pair<Num, Num> p -> unitM(Num(p.a().n + p.b().n));
    default -> unitM(Wrong.INSTANCE);
  };
}

// def apply(a: Value, b: Value): M[Value] = a match {
//   case Fun(k) => k(b)
//   case _ => unitM(Wrong)
// }
static M<Value> apply(Value a, Value b) {
  return switch (a) {
    case Fun fun -> fun.f.apply(b);
    default -> unitM(Wrong.INSTANCE);
  };
}

// def interp(t: Term, e: Environment): M[Value] = t match {
//   case Var(x) => lookup(x, e)
//   case Con(n) => unitM(Num(n))
//   case Add(l, r) => for (val a <- interp(l, e);
// 		   val b <- interp(r, e);
// 		   val c <- add(a, b))
//                     yield c
//   case Lam(x, t) => unitM(Fun(a => interp(t, Pair(x, a) :: e)))
//   case App(f, t) => for (val a <- interp(f, e);
// 		   val b <- interp(t, e);
// 		   val c <- apply(a, b))
// 	      yield c
// }
static M<Value> interp(Term t, List<Pair<String, Value>> e) {
  return switch (t) {
    case Var var -> lookup(var.x, e);
    case Con con -> unitM(Num(con.n));
    case Add add -> {
      var a = interp(add.l, e);
      var b = interp(add.r, e);
      add(a.value, b.value);
    }
    case Lam lam -> unitM(Fun(a -> interp(lam.body, cons(Pair(lam.x, a), e))));
    case App app -> {
      var a = interp(app.fun, e);
      var b = interp(app.arg, e);
      apply(a.value, b.value);
    }
  };
}
```

Here's the full interface:
```java

public interface SimpleInterpreter {
  record M<A> (A value) {
    <B> M<B> bind(Function<A, M<B>> k) {
      return k.apply(value);
    }

    <B> M<B> map(Function<A, B> f) {
      return bind(x -> unitM(f.apply(x)));
    }

    <B> M<B> flatMap(Function<A, M<B>> f) {
      return bind(f);
    }
  }

  static <A> M<A> unitM(A a) {
    return M(a);
  }

  static String showM(M<Value> m) {
    return m.value.toString();
  }

  sealed interface Term permits Var,Con,Add,Lam,App {}
  record Var(String x) implements Term {}
  record Con(int n) implements Term {}
  record Add(Term l, Term r) implements Term {}
  record Lam(String x, Term body) implements Term {}
  record App(Term fun, Term arg) implements Term {}

  sealed interface Value permits Num,Fun,Wrong {}
  record Wrong() implements Value {
    public static final Wrong INSTANCE = new Wrong();
    public String toString() {
      return "wrong";
    }
  }
  record Num(int n) implements Value {
    public String toString() {
      return Integer.toString(n);
    }
  }
  record Fun(Function<Value, M<Value>> f) implements Value {
    public String toString() {
      return "<function>";
    }
  }

  static M<Value> lookup(String x, List<Pair<String, Value>> e) {
    if (e.isEmpty()) {
      return unitM(Wrong.INSTANCE);
    }
    var first = e.get(0);
    return first.a().equals(x) ? unitM(first.b()) : lookup(x, e.subList(1, e.size()));
  }

  static M<Value> add(Value a, Value b) {
    return switch (Pair(a, b)) {
      case Pair<Num, Num> p -> unitM(Num(p.a().n + p.b().n));
      default -> unitM(Wrong.INSTANCE);
    };
  }


  static M<Value> apply(Value a, Value b) {
    return switch (a) {
      case Fun fun -> fun.f.apply(b);
      default -> unitM(Wrong.INSTANCE);
    };
  }

  static M<Value> interp(Term t, List<Pair<String, Value>> e) {
    return switch (t) {
      case Var var -> lookup(var.x, e);
      case Con con -> unitM(Num(con.n));
      case Add add -> {
        var a = interp(add.l, e);
        var b = interp(add.r, e);
        add(a.value, b.value);
      }
      case Lam lam -> unitM(Fun(a -> interp(lam.body, cons(Pair(lam.x, a), e))));
      case App app -> {
        var a = interp(app.fun, e);
        var b = interp(app.arg, e);
        apply(a.value, b.value);
      }
    };
  }

  static String test(Term t) {
    return showM(interp(t, List.of()));
  }

  static void main(String[] args) {
    var term0 = App(Lam("x", Add(Var("x"), Var("x"))), Add(Con(10), Con(11)));
    var term1 = App(Con(1), Con(2));

    System.out.println(test(term0));
    System.out.println(test(term1));
  }
}
```

### PR DESCRIPTION
**Pull request by Randgalt**
Java 17 version by @GavinRay97

Closes #1

### CODE REVIEW

File: java-17/src/main/java/examples/SimpleInterpreter.java [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+        if (e.isEmpty()) {
+            return unitM(Wrong.INSTANCE);
+        }
+        var first = e.get(0);
+        return first.a().equals(x) ? unitM(first.b()) : lookup(x, e.subList(1, e.size()));
+    }
+
+    static M<Value> add(Value a, Value b) {
+        return switch (Pair(a, b)) {
+            case Pair p && p.a() instanceof Num pa && p.b() instanceof Num pb -> unitM(Num(pa.n + pb.n));
```
Comment (Randgalt) [inline java-17/src/main/java/examples/SimpleInterpreter.java]: This line needs work FYI
